# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cmdb', '0003_auto_20180702_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserType')),
            ],
        ),
    ]
